print('Hello, nice to meet you. Welcome to thh coding lab!')
name = input('請輸入您的名字：  ')
print('Hi',name,'Today is your first day in the lab so we would like to know more about you')
age = input('How old are you?　　')
motivation = input('Why do you want to learn python?　　')
print('       ')
print('       ')
print('       ')
print('       ')
print('       ')
print('Great! Now we know you well')
print('we know you are',age)
print(motivation)
print('wish you a interesting learning journey!')